### ISSUE TITLE
Allow multiple HTTP Listeners on same port

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#1690]
Allow multiple HTTP Listeners on same port as long as they have different context paths. For example:

Listener 1: http://localhost:81/foo
Listener 2: http://localhost:81/bar

This is dependent on MIRTH-1691.

Imported Issue. Original Details:
Jira Issue Key: MIRTH-1702
Reporter: geraldb
Created: 2010-12-17T15:42:27.000-0800

**Comment by rbeckman-nextgen** [comment]
This should be done alongside MIRTH-1624, perhaps sharing the servers on the same ports together.  This would mean changing the web service receiver to use Jetty like the HTTP Listener does.

Imported Comment. Original Details:
Author: jacobb
Created: 2010-12-17T16:43:16.000-0800

**Comment by rbeckman-nextgen** [comment]
The SSL Manager also needs to be updated to support this change.

Imported Comment. Original Details:
Author: geraldb
Created: 2011-10-18T16:47:11.000-0700

**Comment by rbeckman-nextgen** [comment]
After doing some research on this, it may be worth asking if we _really_ need HTTP and Web Service Listener connectors to be able to share the same server instance. Jetty **does not support** any SOAP web service APIs (e.g. JAX-WS, JAXB), nor does it integrate with any SOAP web service dedicated stacks (e.g. Metro, which implements JAX-WS anyway). It supports a lot of things (JMX, SPDY, NPN, FastCGI, JNDI, JAAS, WebSocket, OSGi), but SOAP web service support is not one of them. [http://stackoverflow.com/a/8675114]

There _is_ a somewhat old project out there specifically for integrating JAX-WS endpoint publishing into a Jetty server ([J2se6HttpServerSPI](http://docs.codehaus.org/display/JETTY/J2se6HttpServerSPI)). I think it is consistently updated to work with the latest Jetty version (we use 7.6.7, latest stable is 9.1.5), but it doesn't look like it has been in active development since 2009. Anyway other than that, there are a couple of problems with this "solution".

First, it relies on a System.setProperty call beforehand so that all published Endpoints use a custom HttpServerProvider. This means that all published Endpoints across the JVM will use the custom provider specific to Jetty, so from then on you can't use JAX-WS to integrate with a standard com.sun.net.httpserver.HttpServer. Also, the provider _appears_ to use only a single Jetty server, so it will probably have to be overridden so that multiple server instances can be used (for different host/port bindings).

Second, it does not support HTTPS. Literally the createHttpsServer method of the provider just throws an UnsupportedOperationException. It _looks_ like you can get around that by first setting the appropriate SSL connectors on the Jetty server, then passing that into the provider's setServer method. Not sure yet what implications that might have, but it seems as if this is the de facto method of using JAX-WS inside Jetty (at least, if the couple of blogs I found are to be believed). At the worst, it may require implementing createHttpsServer ourselves, and from what I've seen that may be quite an undertaking.

I'm not 100% sure if this custom provider will work for everything that we want it to (sharing a common server across HTTP and Web Service Listeners, being able to support advanced web services that can handle complex objects rather than a single literal, HTTP proxy servers, custom SSL contexts, WADL, etc.). More research and a somewhat in-depth proof of concept would have to be done to see how feasible this all is in the first place.

Of course if having HTTP Listeners and Web Service Listeners share the same server isn't a hard requirement then this is all moot, and the issue becomes relatively easy (just do different things for the HTTP Jetty Server and the WS HttpServer).

Imported Comment. Original Details:
Author: narupley
Created: 2014-05-27T06:14:34.000-0700

**Comment by rbeckman-nextgen** [comment]
I can see some arguments for having multiple WS Listeners share the same server, and multiple HTTP Listeners share the same server, but I don't think HTTP and WS Listeners sharing the same server is a hard requirement or even all that useful. The new HTTP Listener features will make the WS Listener a more specific and less used connector, anyway.

Imported Comment. Original Details:
Author: jacobb
Created: 2014-05-27T09:39:53.000-0700

**Comment by rbeckman-nextgen** [comment]
Hey guys. This change is really important to be able to use Mirth to implement CDS Hooks (newer technology). I'm trying to do this now with Mirth and this ticket is my only blocker. It would be huge if we can use Mirth for this new technology.

So, to implement CDS Hooks successfully, I need multiple Mirth channels to use the same base context (which includes same port). 

Examples:
-HTTP Listener Channel #1: CDS Service - Discovery Endpoint:     http://localhost:80/cds-services/
-HTTP Listener Channel #2: CDS Service - Patient View Endpoint: http://localhost:80/cds-services/patient-view/

This would be huge, if I could use Mirth to do this with all my CDS Hooks clients.

Here is the spec:
>https://cds-hooks.org/specification/current/#calling-a-cds-service
>https://cds-hooks.org/specification/current/#discovery

I would love some input and perspective on if/when this ticket will be completed.

Thanks so much,
Vivian

Imported Comment. Original Details:
Author: vsortiz
Created: 2020-02-09T14:04:13.000-0800

**Comment by rbeckman-nextgen** [comment]
@[~vsortiz] You can do this in mirth by having a single channel listen on the port and route requests to your other channels based on context path via channel writers or manually via User API called in javascript.

Alternatively, you can set up a reverse proxy/API gateway in front of mirth and use it to forward requests to the correct channel.

Imported Comment. Original Details:
Author: agermano
Created: 2020-02-17T14:34:21.000-0800

**Comment by DurgpalSingh** [comment]
Can you provide any sample code or documentation.

**Comment by petermicuch** [comment]
@[~agermano] you can indeed setup reverse proxy in front of Mirth and have dedicated context path for each HTTP listener, but then you are loosing advantage of having Mirth connect as single point for device configuration. For any new context path, you have to also touch your reverse proxy/ingress (kubernetes servis that might be behind reverse proxy and in front of mirth) and route your requests to correct port. Today instead of setting your reverse proxy to route all "/mirt-device" requests to port 80 of mirth connect and then just creating HTTP listeners in mirth only, you have to either always touch you reverse proxy config or play with channel writers. If user is trying to use the same port for 2 HTTP listeners, why not to create hidden channel that routes requests to other channels based on context path as you described? Would that be something that would fit into concept?

**Comment by ppazos** [comment]
Not sure why WS and SOAP was mentioned here, the original request seems to be about HTTP Listeners not Web Service Listeners.

Setting up different paths on the same port would be desirable for any API-like implementation on Mirth, using different channels as entry points.

**Comment by pacmano1** [comment]
You can parse the context path and do whatever you want including splitting out processing to different channels and/or destinations.  Effectively the main http listener can be just a dumb "router" based on context path it sees on the inbound request.  Typically I validate the context path, the content and the token in the main listener source side and use destination set filtering as needed for the rest of the message logic.

**Comment by ppazos** [comment]
@pacmano1 I have considered that, though it's like implementing an HTTP Listener in code. I can also use my own HTTP server, do everything there, then forward to Mirth. Both things add extra complexity to the overall architecture, and it could be done by the default HTTP Listener using just configuration. It's a matter on how the internal web server is configured. It seems right now it's being instantiated once per channel, so once per port, and the context path doesn't play any role there, where usually in a web server the port is always the same and different behavior is reached by using different context paths.

Maybe it'll better to instantiate one server per port and add all context paths to it, even with context paths from different channels. Then if channels use different ports, instantiate another server on that port.

I guess with this multi-channel approach, the difficult part would be how to handle the configuration for the processing threads, since those are configured per channel. I'm not sure if the web server allows to configure threads per context path.
