### ISSUE TITLE
Option "Include All Subdirectories" doesn't work in File Reader with SFTP

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3631]
Morning,

Currently, I use Mirth Connect 3.2.2.7694 and I have an issue with the option "Include All Subdirectories" in my File Reader connector with SFTP method.

Apparently, the reading is not done in the subdirectories of the source path.

This happen only with SFTP method, with the other methods, this option works fine and I can read through the subdirectories.

Thank you in advance to all for your help.

Regards

Imported Issue. Original Details:
Jira Issue Key: MIRTH-3745
Reporter: c3g
Created: 2015-07-07T01:12:08.000-0700

**Comment by is-simon** [comment]
@cturczynskyj 

Using Mirth 4.4.1 here...

I would like to reopen this one since I think it's a major issue with the FileReader using SFTP.

I also thought at first that the "Include All Subdirectories" didn't worked, but in fact it's because the connector enters an infinite loop and never comes back from it's first poll.

This is because the list directories include both "." and ".." directories, which should be excluded from the recursion.

Here's a image of my debbugger while inverstigating this problem, showing the directoryStack field.

![list File Recursively infinite loop](https://github.com/nextgenhealthcare/connect/assets/48103155/7b9ba83b-e4d4-412f-a71e-97f6c3427a62)

I successfully fixed the problem on my local machine by changing the `SftpConnection#listDirectories` function from this:
```java
@Override
public List<String> listDirectories(String fromDir) throws Exception {
    List<String> directories = new ArrayList<String>();

    cwd(fromDir);

    @SuppressWarnings("unchecked")
    Vector<ChannelSftp.LsEntry> entries = client.ls(".");

    for (Iterator<ChannelSftp.LsEntry> iter = entries.iterator(); iter.hasNext();) {
        ChannelSftp.LsEntry entry = iter.next();

        if (entry.getAttrs().isDir() || entry.getAttrs().isLink()) {
            directories.add(new SftpFileInfo(fromDir, entry).getAbsolutePath());
        }
    }

    return directories;
}
```
to this
```java
@Override
public List<String> listDirectories(String fromDir) throws Exception {
    List<String> directories = new ArrayList<String>();

    cwd(fromDir);

    @SuppressWarnings("unchecked")
    Vector<ChannelSftp.LsEntry> entries = client.ls(".");

    for (Iterator<ChannelSftp.LsEntry> iter = entries.iterator(); iter.hasNext();) {
        ChannelSftp.LsEntry entry = iter.next();

        if ((entry.getAttrs().isDir() || entry.getAttrs().isLink()) && !".".equals(entry.getFilename()) && !"..".equals(entry.getFilename())) {
            directories.add(new SftpFileInfo(fromDir, entry).getAbsolutePath());
        }
    }

    return directories;
}
```

But I'm not sure it is the right way to fix this soo I'll let you decide.
