### ISSUE TITLE
When the advanced clustering plugin is installed, the alerting page appears to be missing the triggered, Current level, and last level change values

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#4351]
Actual Outcome:  When the advanced clustering plugin is installed and enabled, the alerting page appears to be missing the triggered, Current level, and last level change values.
Expected Outcome:  Trigger, Current Level, and Last Level should show values independent of the Advanced Clustering plugin being enabled
Setup Steps (Pre-reqs):  Install both the Advanced Clustering and Advanced Alerting plugins.  Set up a simple alert.  With Advanced Clustering enabled, the triggered, Current level, and last level change values are missing
Steps to Reproduce:  Same as setup steps
Reported Site/Versions: Mirth Connect 3.8

Additional Info:
What is the workaround (if applicable)?:  Disable the Advanced Clustering Plugin

Imported Issue. Original Details:
Jira Issue Key: MIRTH-4476
Reporter: han
Created: 2019-12-05T11:14:53.000-0800

**Comment by RunnenLate** [comment]
This appears to still be an issue as on version 3.10.1  With the advanced clustering plugin enabled the "trigger count", "current level", and "last level change" all show as "--" and do not update correctly.  the blue and yellow instance below is our production environment with clustering enabled.  the red is our dev environment where clustering is not set up.  

![image](https://user-images.githubusercontent.com/2079191/189200102-e5103f6e-8b35-434e-aa38-66f62bd264a5.png)

**Comment by RunnenLate** [comment]
It looks like this issue is more serious than just the values not being shown.  In my testing, it looks like a message needs to be sent to each server within the cluster for it to read the trigger. Thus if all inbound messages via HTTP are going to server 1.  Because server 2 did not get a message the alert will trigger.  

--To create the issue 
Setup up two identical servers with the clustering plugin installed
Create an HTTP channel 
Configure alerting with the following configurations: 
![image](https://user-images.githubusercontent.com/2079191/189231677-6df95471-4201-46e0-a5a7-bdac989e3203.png)
continuously  HTTP messages to the port for the channel you just created using the virtual IP shared between the two servers. 
Alter will trigger after 1 minute to Level 2

--
If a message is sent directly to both server 1 and server 2 alert window the level will return to normal. 

--workaround
None with the clustering plugin

**Comment by RunnenLate** [comment]
I'm going to ask that this bug be closed as the original issue regarding the data missing from the alert view is fixed as of version 3.12. A separate issue opened for the second issue described above. https://github.com/nextgenhealthcare/connect/issues/5415
