### ISSUE TITLE
API S3

### ISSUE THREAD

**Issue by boukenka** [nextgenhealthcare/connect#4390]
Hello,

Today it is only possible to use the AMAZON S3 for the API S3 in the File Reader / Writer connector.
Or there are many other solutions using API S3 e.g. MiniIO
Could it be added?

Configuration: Mirth 3.9.0

**Comment by boukenka** [comment]
Is it possible to get an answer?

**Comment by ruqez** [comment]
Our organization would also greatly appreciate the ability to define a custom endpoint host in the new S3 connector in order to connect directly to our on-premise FlashBlade Object Store (self-hosted S3 solution) and it would be nice to allow our developers to be able to connect to Docker images running MinIO (as @boukenka mentioned).

All that would be needed is the addition of a field which would then populate the `withEndpointConfiguration` in the `AmazonS3ClientBuilder`

Example: `AmazonS3ClientBuilder.withEndpointConfiguration(new AwsClientBuilder.EndpointConfiguration("http://self-hosted-s3.example.com:9000", Regions.US_EAST_1.name()))`

**Comment by boukenka** [comment]
Closing the issue as no feedback has been received after almost 9 months.

**Comment by pjlammertyn** [comment]
Should be reopened
