### ISSUE TITLE
Update Apache Commons Collections to 4.4

### ISSUE THREAD

**Issue by cturczynskyj** [nextgenhealthcare/connect#4428]
The current version has these vulnerabilities:

- CVE-2017-15708
- CVE-2015-6420
- CVE-2015-4852
- CVE-2015-7501
- CVE-2019-13116

Updates:
- Apache Commons Collections4: 4.0 -> 4.4
- Apache Commons Collections: 3.2.1 -> DELETE
- Apache Commons Configuration2: 2.7
- Apache Commons Configuration: 1.7 -> DELETE
- Apache Velocity: 1.7 -> 2.2
- Apache Velocity Tools: 2.0 -> 3.0

**Comment by ChristopherSchultz** [comment]
CVE-2017-15708 is not relevant. It is filed against Apache Synapse which is not used by Mirth.
CVE-2015-4852 is not relevant. It is filter against WebLogic Server which is not used by Mirth.
CVE-2015-7501 is not relevant. It it filed against JBoss Servet which is not used by Mirth.
CVE-2019-13116 is not relevant. It it files against Mule Server which is not (no longer) used by Mirth.

The real issue is CVE-2015-6420 which has been patched in commons-collections(3) v3.2.2. A simple version-bump would have resolved the security issue.

Please don't make security issues appear to be bigger than they are.

Also, please make the smallest change possible to mitigate or resolve a security issue. Otherwise, you end up with [downstream effects](https://github.com/nextgenhealthcare/connect/issues/4435) from your solutions.
