### ISSUE TITLE
Not able to post HL7 message over TCP/MLLP using C#

### ISSUE THREAD

**Issue by zeecorleone** [nextgenhealthcare/connect#4481]
When posting message through TCP/MLLP using C#, it hangs on reading response, although the connection was successful. For example, as shown in the following code, stream.Write executes, but when stream.Read executes, it stays for ever. Is there something I'm missing? The message is wrapped inside <VT> and <FS><CR>. I expect the server to say something. If it will give me error at least, I'll have clue to fix and proceed. 

                stream.Write(data, 0, data.Length);
                data = new Byte[256];
                String responseData = String.Empty;
                Int32 bytes = stream.Read(data, 0, data.Length);

**Comment by tonygermano** [comment]
Have you looked at the server to see if any messages are being generated or any errors are being logged? You said you are sending with MLLP, but I don't see the framing characters. Are they included in the data? My guess is that if it is hanging rather than returning an empty response that mirth doesn't know you are finished sending the message and doesn't try to create the message until you disconnect, at which point it's too late to send you a response.

This question should probably be asked in the [user forums](https://forums.mirthproject.io/forum/mirth-connect/support) or [slack](https://forums.mirthproject.io/forum/mirth-connect/support/15720-join-the-mirth-connect-slack-channel) rather than a bug report.
