### ISSUE TITLE
Re-open Unable to Halt a database connector that hangs in 'Polling' state. #3304... please 

### ISSUE THREAD

**Issue by pacmano1** [nextgenhealthcare/connect#4666]
Self explanatory.

**Comment by jonbartels** [comment]
Linking to #3304 . Looks like the issue existed as recently as 2020.

@pacmano1 was this resolved or mitigated by any of the library updates in 3.10 or 3.11?

**Comment by tonygermano** [comment]
7 days ago, a user commented the issue still exists in 3.11.0. The original issue that was opened in 2015 was never resolved, but closed for inactivity. 5 different users have commented that the problem still exists for them since the issue was closed 5 months ago. I know this issue had a ton of upvotes under Jira before it was migrated to github.

It was flagged with the Future Planned milestone, so they already planned to eventually do something about it. Nick Rupley proposed a solution in a comment 6 years ago.

**Comment by pladesma** [comment]
We've reopened https://github.com/nextgenhealthcare/connect/issues/3304.
