### ISSUE TITLE
[BUG] Mirth Connect Administrator Launcher generating SYN FLOOD attack reports on firewall

### ISSUE THREAD

**Issue by nicovn** [nextgenhealthcare/connect#4807]
When verifying the signature of the JARs Mirth Connect Administrator Launcher opens hundreds of TCP connections simultaneously to ocsp.digicert.com on port 80 which is causing our firewall (Palo Alto PA-220) to see this traffic as a SYN FLOOD attack.

**Screenshots**
cfr attached screenshot
![mirth-launcher-syn-flood](https://user-images.githubusercontent.com/4510176/138118960-6d3f8aba-70df-436d-adab-455ab4bf07de.PNG)

**Workaround(s)**
Block outgoing traffic on port 80 in Windows Defender Firewall for applications launcher.exe and launch.exe

**Comment by ab-20-m** [comment]
As a comparison to the behavior of Java Web Start: JWS appears to cache the OCSP responses and not re-validate if a certificate in the chain was already validated. MCAL appears to verify the full cert chain for every signed JAR even though all the JARs with a standard Mirth Connect distribution should have been signed by the same code signing cert and have the same trust anchors.

**Comment by jonbartels** [comment]
The OCSP behaviors shown here are a symptom of the threading issue in #4866. MCAL should be checking OCSP lists to prevent plugins signed with revoked certs from being trusted. MCAL should be caching or coordinating these requests across threads to not generate this SYN-flood behavior.

I think this issue should be closed and focus on #4866 since coordinating the multithreading behaviors may allow for additional efficiencies when launching MC with MCAL and also fix the OCSP spam.

**Comment by jonbartels** [comment]
https://github.com/nextgenhealthcare/connect/issues/5287 should resolve this issue once it is implemented.
