### ISSUE TITLE
[BUG] Unable to bind TCP listener to localhost (127.0.0.1 or 127.0.0.2 e.g.)

### ISSUE THREAD

**Issue by nicovn** [nextgenhealthcare/connect#5161]
**Describe the bug**
When you fill in localhost or 127.0.0.1 (or even 127.0.0.2) the TCP listener connector binds to ALL (!) addresses (0.0.0.0). This is a potential security risk.

The issue doesn't occur when you fill in 127.0.0.1 for a HTTP listener connector, in that case Mirth binds correctly to localhost.

**To Reproduce**
You can easily verify using

netstat -anp | grep tcp | grep LISTEN

**Expected behavior**
The TCP listener is correctly bound to 127.0.0.1 when you fill in 127.0.0.1 in the field "Local address - Specific Interface"

**Actual behavior**
The TCP listener binds to all interfaces (0.0.0.0)

**Screenshots**
not applicable

**Environment (please complete the following information):**
 - OS: CentOS
 - Java Distribution/Version OpenJDK 11
 - Connect Version 4.0.1 (and all others before)

**Workaround(s)**
Configure a firewall rule to block all inbound traffic to that port

**Additional context**

**Comment by jonbartels** [comment]
I am not sure of the answer or solution. I had a look at the TCP code and I think your question could be answered by tracing calls to `com.mirth.connect.connectors.tcp.TcpReceiver#getLocalAddress` (https://github.com/nextgenhealthcare/connect/blob/e66d1122dbeebfcf5a8939beb93d720b2d5071fb/server/src/com/mirth/connect/connectors/tcp/TcpReceiver.java#L1050) 

`com.mirth.connect.connectors.tcp.SocketUtil#createSocket(com.mirth.connect.connectors.tcp.TcpConfiguration, java.lang.String, int)` also seems relevant. 

Is that address ever normalized or interpreted such that `127.x.x.x` IPs are normalized to something that binds to all addresses?
MC will call core JVM code to create sockets. Does that code do any normalization or interpretation of the address?

I hope this helps OP or the MC devs track down a better solution.

**Comment by rpotter9** [comment]
@pladesma 
Are you able to update the 4.3.0 upgrading wiki to include this? We've just been caught out by this change as we had an pre-existing channel set to 127.0.0.1 and has moved several servers since the channel was created and the latest servers have multiple IP addresses bound, and this has subsequently stopped receiving messages from our supplier. 

Obviously, the quick fix was just to the option to "All interfaces" and restart the channel again, but we were only notified by our supplier when they couldn't send any messages to us since the upgrade. 

Just worth pointing out to other people to double-check their bindings if they've used a localhost address in TCP Receiver.
