### ISSUE TITLE
Exports messages into a specific directory path  api is throwing nullponit error

### ISSUE THREAD

**Issue by abhishek-1222** [nextgenhealthcare/connect#5203]
I am trying to access  `api/channels/channelId/messages/_export`  but it's throwing nullpoint error even after passing channel id .
Which parameters are required to pass in these api ?

**Comment by jonbartels** [comment]
A user in Slack had the same issue - https://mirthconnect.slack.com/archives/C02SW0K4D/p1652878052307989

This issue is probably similar to https://github.com/nextgenhealthcare/connect/discussions/4638

Do an export from the MC GUI then go look at Events. It should record what parameters were passed to do the export, you can then use the same parameters in your API call.

Please also post any errors from your `mirth.log`
