### ISSUE TITLE
[IDEA] Improve launch time when using the Administrator Launcher without internet access

### ISSUE THREAD

**Issue by pladesma** [nextgenhealthcare/connect#5287]
When a user launches the Administrator using the Administrator Launcher, and they don’t have internet access, it can take a very long time to launch because the signature verifications takes a long time to time out.

**Potential Solutions**

- Maybe we can cache the signature verification status for the jars

- This wouldn’t help users who don’t have internet access, but it would speed up the process for others

- Reduce the timeout for each signature verification. If we can’t reach the verification server, show a warning, but start the Administrator anyway.

- Maybe make signature verification/revocation checking configurable?

Related Discussion: https://github.com/nextgenhealthcare/connect/discussions/4944

**Comment by jonbartels** [comment]
Other potential solutions, both are caching related:

* MCAL appears to use Apache Commons HTTP Components v 4.5.13 . Maybe a caching HTTP client would help? https://hc.apache.org/httpcomponents-client-4.5.x/current/tutorial/html/caching.html . From a small log sample on discussion 4494 we see `Cache-Control: 'max-age=158059'` so at least one OCSP endpoint allows for HTTP level caching
* MCAL does not currently use Guava but MC does. Guava has a good caching feature set https://github.com/google/guava/wiki/CachesExplained . A cache could be created such that the cache key is for the certificate being checked. Then implement a `build` method that makes the actual CRL/OCSP checks. So if the key is being checked, new checks will wait, then any duplicate checks will just hit the local cache. This cache is not persistent so the checks would happen each time MCAL starts MC.

Any caching solution should only cache the requests at in memory. Caching CRL/OCSP checks persistently to disk would defeat the purpose of CRL and OCSP. 

> Maybe make signature verification/revocation checking configurable?

Giving normal users options to turn OFF security checks with a radio button isn't great. I advocate for making these checks more efficient first. I think for at least one of the users the connection got blocked in the first place because of the excessive number; they wouldn't have been blocked if they made fewer HTTP requests.

More efficient requests will help nearly all users, then users without internet connections can have an optional `--no-internet` flag for MCAL for their use case.

EDIT: Followup thought on HTTP caching, I wonder what those caches do for timeouts or errors. For the stated issue with unreachable CRL/OCSP endpoints would the cache store the failure and make subsequent requests also fail from the cache OR would the cache not cache the failure and retry the request over and over (thus defeating the stated goal to tolerate no internet connections)

As you can see I am clearly invested and excited about this problem. Please do engage me (or tell me to chill!) if I can help.

**Comment by jonbartels** [comment]
@pladesma - I remain eager to help fix this issue. Can I do anything to help?

At my day job, a platinum customer of NextGen, I have users who see slow start times from MCAL.
As an open-source user, I am eager to help fix this. I had fun testing it last summer but I can't see the source code to help. I'm betting its a simple synchronization or caching solution.
There are several other users pointing out how this is slow.

How can I help solve this directly as an engineer?
How can I help solve this as a user and customer? Need a beta tester?

**Comment by pacmano1** [comment]
If you configure your local or corporate firewall to issue a reject rather than a block, there appears to be no hang.

The difference between block and reject is that with reject, a packet (TCP RST or ICMP port unreachable for UDP) is returned to the sender (the MCAL), whereas with block the packet is dropped silently.
