### ISSUE TITLE
[BUG] Mirth Connect Login with LDAP Plugin is Case-sensitive for Username

### ISSUE THREAD

**Issue by jdonextgen** [nextgenhealthcare/connect#5396]
**Describe the bug**
Users are unable to use their LDAP login unless they used all lowercase characters for their username. This bug is reproducible.

**To Reproduce**
1. Setup LDAP
2. Create credentials in LDAP where the username contains at least one capital letter.

1. Setup Mirth Connect with LDAP
2. Login using credentials created in LDAP
3. See error

**Expected behavior**
Users should be able to to use their LDAP login with a case-insensitive username.

**Actual behavior**
Users are unable to use their LDAP login unless they used all lowercase characters for their username.

**Screenshots**
N/A

**Environment (please complete the following information):**
 - OS: [e.g. Linux (CentOS), Windows 10, MacOS]
 - Java Distribution/Version [e.g. OpenJDK 11, Java 8 (201)]
 - Connect Version [e.g. 3.8.0]: 3.10.1

**Workaround(s)**
1. Login with LDAP credentials using all lowercase for the username
OR
1. Login as a user with privileges to modify users
2. Modify username of LDAP user to match the casing in the LDAP username
3. Logout and login using LDAP credentials with the specified casing

**Additional context**
N/A

**Comment by jonbartels** [comment]
Holy crap! It finally got fixed!

**Comment by jonbartels** [comment]
@jdonextgen  This fixes KI197032 and KI177637 right? If it does please update those KIs and please highlight this issue in the release notes. I don't know if I can truly convey what a big deal this bug was.

The underlying problem that my team observed externally was that LDAP did a `search` (case sensitive) before trying the `bind` (not case sensitive). Can you roughly describe the implemented solution? Do you still do the search or just jump straight to the bind like most other LDAP tools do?

**Comment by jdonextgen** [comment]
@jonbartels Yeah, this bug fix should fix KI197032 and KI177637. From what I've been told, we still do the search but it's now case-insensitive.
