### ISSUE TITLE
[IDEA] Automatically hash outgoing messages

### ISSUE THREAD

**Issue by pladesma** [nextgenhealthcare/connect#5494]
Automatically generate a SHA-256 hash for each outgoing message. Make the hash available as a velocity variable `${HASH}` in each Destination connector. It should also be available as a drag-and-drop variable `Message Hash` from the Destination Mappings list.

This feature would make it simpler to implement a way of ensuring message integrity, meaning ensuring that the message hasn't been altered in transit.

**Comment by jonbartels** [comment]
Would this hash be computed on the entire message or a configurable portion of the message?

I ask because hashing for validation is one thing. That would be the hash of the full content.

A related use case is message deduplication - So you might have HL7 messages where an EMR (cough Epic cough) spams out ADTs where only the MSH segment differs but all other data is the same. 

Is this case related to https://github.com/nextgenhealthcare/connect/issues/5476 ?
