### ISSUE TITLE
[BUG] Unable to import channel if ".xml" extension isn't specified

### ISSUE THREAD

**Issue by elavy-harris** [nextgenhealthcare/connect#5516]
**Describe the bug**
Error trying to import channel if ".xml" is not included explicitly.

**To Reproduce**
1. Click "Import Channel"
2. Type the name of a channel file, but do _not_ type ".xml"
3. See error

**Expected behavior**
Channel imports normally.

**Actual behavior**
Import displays errors consistent with the file not existing. (First "Unable to read file", then "The channel is being imported from an unknown or older version of Mirth Connect".

**Environment (please complete the following information):**
 - OS: Windows 10
 - Connect Version [e.g. 4.1.1]

**Workaround(s)**
Type the full filename or select from the directory list.

**Comment by NoraTheExplorer** [comment]
I think it works as expected. This is the normal file picker.
Was this different in prior versions?

**Comment by elavy-harris** [comment]
> I think it works as expected. This is the normal file picker. Was this different in prior versions?

I don't know how it worked in prior versions. Probably the same way.

When the "files of type" dropdown is set to "XML Files", my expectation is that files will be assumed to have that extension. I could understand having the extension not auto-selected when searching "All files".

This may be behavior inherited from the underlying architecture (Java?), in which case there's probably nothing that can be done about it.

**Comment by tonygermano** [comment]
Does clicking on the file rather than typing it include the `.xml` extension?

**Comment by elavy-harris** [comment]
> Does clicking on the file rather than typing it include the `.xml` extension?

Yes.

**Comment by brianlaclair** [comment]
> > Does clicking on the file rather than typing it include the `.xml` extension?
> 
> Yes.

I'd have to disagree that this is a bug in that case, and defer to @NoraTheExplorer 's response as accurate.
Technically you are selecting the file `/exampleDir/example` rather than `/exampleDir/example.xml` - MC is accurately telling you that file does not exist. 

It is worth noting that the file extension has no bearing on whether or not MC can import the channel - in fact, you could give your files no extension at all, or something like ".elavy-harris" and still have MC correctly import them, as long as the complete file path is specified.

**Comment by pladesma** [comment]
Closing the issue. As others have mentioned, this is the expected behavior.
