### ISSUE TITLE
[BUG] Protection of stored user passwords is not sufficient for modern usage

### ISSUE THREAD

**Issue by ChristopherSchultz** [nextgenhealthcare/connect#5665]
Now that the code for [`Digester` has been made public](https://github.com/nextgenhealthcare/connect/commit/0d74442e14ad90ae1cf91a041adb5802002b2399#diff-cb5ff6185ec7679052866dd272d4ba0da6299537945f22ca8da84d5ff61f3eee), I can comment on its operation.

The default operation of the `Digester` (which is used to hash passwords for storage in Mirth's user database) uses an 8-byte salt and 1000 rounds of the MD5 hashing algorithm, with the salt being applied a single time. This should be updated to modern practices:

* As FIPS compliance is likely desired, PBKDF2 should be used (If FIPS is not important, scrypt or Argon2 should be preferred)
* The number of hashing rounds for PBKDF2 should be several orders of magnitude higher than current [OWASP suggests 600,000 rounds](https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html)

Stored credentials can be upgraded in-place any time a user successfully authenticates to Mirth:

1. Fetch the credential from the database
2. Check the password "version" (at this point, simply checking the length in bytes should be sufficient)
3a. If the version is old, use the older hashing algorithm on the unverified password and compare to the stored credential. If the password matches, re-rehash the unverified password using the new algorithm and update the stored credential in the db; return "authorized". Otherwise, return "unauthorized".
3b. If the version is new, use the new hashing algorithm on the unverified password and compare. If the password matches, return "authorized", otherwise return "unauthorized".

**Comment by narupley** [comment]
It will actually use SHA-256, not MD5, because the Digester is always initialized with the algorithm from the MC encryption config. Unless you have overridden `digest.algorithm` in your mirth.properties file.

But even so, that default should be changed in the Digester class itself too. And we should update the default parameters to one of the more modern recommended approaches too.

**Comment by ChristopherSchultz** [comment]
It looks like Bouncy Castle has an implementation of Argon2 already present. I could take a stab at writing a handler for that kind of hashing. I have a preference for pluggable password hashers so I could probably do both that and PBKDF2 and allow the operator to select whichever one they prefer. FIPS may require PBKDF2 which is the only reason I would bother including it.

**Comment by narupley** [comment]
In 4.4 the default will be changed from SHA-256 to PBKDF2WithHmacSHA256, with 600000 iterations. We added support for Argon2 as well.

In addition, new configurable options will be available:
- `digest.saltsizeinbytes`
- `digest.iterations`
- `digest.usepbe`
- `digest.keysizeinbits`
- `digest.fallback.algorithm`
- `digest.fallback.saltsizeinbytes`
- `digest.fallback.iterations`
- `digest.fallback.usepbe`
- `digest.fallback.keysizeinbits`

New _and_ upgraded MC instances will start using the new digest algorithm going forward for any newly created/updated passwords.

The "fallback" properties will also allow MC to still verify old passwords. So after you upgrade MC you can still login with the same credentials. Then you can update your password and the new hash in the database will use the new algorithm.

On upgrade to 4.4 these will be added to mirth.properties (if you had not explicitly set `digest.algorithm` already):

- `digest.fallback.algorithm = SHA256`
- `digest.fallback.iterations = 1000`
- `digest.fallback.usepbe = 0`

Examples:

New defaults:
- `digest.algorithm = PBKDF2WithHmacSHA256`
- `digest.saltsizeinbytes = 8`
- `digest.iterations = 600000`
- `digest.usepbe = 1`
- `digest.keysizeinbits = 256`

Old defaults:
- `digest.algorithm = SHA256`
- `digest.saltsizeinbytes = 8`
- `digest.iterations = 1000`
- `digest.usepbe = 0`

Argon2:
- `digest.algorithm = Argon2id`
- `digest.saltsizeinbytes = 8`
- `digest.iterations = 3`
- `digest.usepbe = 0`
Uses v13 with 12 MB and 1 parallelism. Both `Argon2i` and `Argon2d` are supported too.

**Comment by narupley** [comment]
FYI a bit of additional work was done on this, so that it will allow a set of "fallback" digest settings too. Updated the comment above.

**Comment by ChristopherSchultz** [comment]
> In 4.4 the default will be changed from SHA-256 to PBKDF2WithHmacSHA256, with 600000 iterations. We added support for Argon2 as well.

👍 

> In addition, new configurable options will be available:
>     * `digest.usepbe`

What does this mean? Doesn't the algorithm imply whatever this is?

>     * `digest.keysizeinbits`

What does this mean? None of these hashes use keys.

> New _and_ upgraded MC instances will start using the new digest algorithm going forward for any newly created/updated passwords.
> 
> The "fallback" properties will also allow MC to still verify old passwords. So after you upgrade MC you can still login with the same credentials. Then you can update your password and the new hash in the database will use the new algorithm.

Passwords must be manually-re-hashed, right? Can you just change your password from its current value to it's current value and "update" the stored credential? Or do you need a proper new password. Any reason not to simply auto-upgrade passwords? (I suppose if the Mirth db were being used for other purposes, it might be _surprising_ for password format to change.)

Thanks @narupley and the rest of the team for doing this. It may seem trivial but it's great for overall security and helps move the industry forward from old, common but not-very-secure ways of doing things.

**Comment by narupley** [comment]
The `usepbe` setting is just there because the code needs to decide whether to use a MessageDigest or a SecretKeyFactory + PBEKeySpec. Both take in an arbitrary string for the algorithm. We're not keeping any kind of hard-coded list of which algorithms are "PBE" and which aren't. I suppose we could just check that the string starts with "PBE" or "PBK", but I'm not sure if that would always be correct. Argon2 is a separate special case that doesn't fit into either bucket, so there's a separate conditional branch for that.

The key size is needed for PBE algorithms, because they do indeed generate keys. Such as PBKDF2 (Password-Based **Key Derivation** Function 2).

Yes, you can simply update your password to the same password, and it will be hashed using the new algorithm. Auto-upgrading is not possible because Mirth Connect does not (and should not) know the pre-image plaintext password. You can't update the hash (even using the same algorithm) if you don't know the pre-image input. So each user must update their own password. Or, the Administrator can go in and reset everyone else's password if they want to do it that way.

**Comment by ChristopherSchultz** [comment]
> The `usepbe` setting is just there because the code needs to decide whether to use a MessageDigest or a SecretKeyFactory + PBEKeySpec.

Ah, yes. Easier than special-casing a bunch of things. This could have been done with an algorithm prefix, but meh the work is already done.

> The key size is needed for PBE algorithms, because they do indeed generate keys. Such as PBKDF2 (Password-Based **Key Derivation** Function 2).

Ack.

Any reason why some items are specified in bytes and others in bits? e.g. `saltsizeinbytes` vs `keysizeinbits`?

> Auto-upgrading is not possible because Mirth Connect does not (and should not) know the pre-image plaintext password.

Don't you have the original password before you hash it?

**Comment by narupley** [comment]
Those are also basically just because the salt generator uses SecureRandom which takes in number of bytes, and for the salt it doesn't really make sense to specify anything more granular than bytes. Meanwhile PBEKeySpec takes in the key size in bits, because some PBE ciphers can have variable-size keys where the length does not necessarily need to be divisible by 8.

For the other question, I think I misunderstood what you meant by "auto-upgrading". I thought you meant like, when the server starts up it auto-upgrades all hashed passwords without any human intervention, which is impossible. However, you probably meant that it just updates the password for each individual user upon their next login. Yep that would be feasible, but was not done as part of this work.
