### ISSUE TITLE
MetaAppender logger

### ISSUE THREAD

**Issue by steveFuturePerfect** [nextgenhealthcare/connect#5753]
Hi,

Recently I picked up on the Mirth logging enhancement tool at https://github.com/odoodo/Mirth-MetaAppender

Followed instructions, I've installed the jar etc and its been working well.

But the server log is showing some messages I'm not too sure about, some not related to any channel. They're not causing an issue, as far as I can see, but is there any way to stop these messages being logged?

For example:

- > _[2023-04-17 01:08:19,510] WARN (com.zaxxer.hikari.pool.HikariPool:616): HikariPool-2 - Thread starvation or clock leap detected (housekeeper delta=27m15s595ms964µs600ns)._

- > [2_023-04-12 04:06:15,166] INFO (test_channel-org.quartz.core.QuartzScheduler:534): Scheduler 6d037869-e8ac-45fc-8425-87050f95f834_$NON_CLUSTERED started.
I think this is related to the use of the javascript reader connector and polling.

I wasn't seeing messages such as these before I installed the metaappender.

Thanks

**Comment by jonbartels** [comment]
Cross linking to question in https://github.com/odoodo/Mirth-MetaAppender/issues/4

How are you running Mirth? Locally? Container? VM?

Both errors relate to clock drift. Both the pooler and the scheduler would be sensitive to thinks like the computer sleeping.

**Comment by steveFuturePerfect** [comment]
My Mirth Connect instances are run locally and on remote servers, both displaying the mentioned logged messages.

As its only a warning, nothing too much too worry about?

**Comment by jonbartels** [comment]
Clock drift usually only happens when a physical computer is put to sleep or if a container/VM is paused. If there are not sleeps, pauses, etc. then I would not ignore these warnings. The warnings are telling you a time-sensitive operation failed or was reset after clock drift was detected. 

Possible causes of clock drift WITHOUT a sleep or pause could be:
* poor time sync (are you running NTP to maintain system time?)
* extremely high CPU load

I suspect that you've had the warnings happening for a long time but the MetaAppender made it easier to see the errors. That is a good thing. That is what the Meta Appender does for its users!

**Comment by steveFuturePerfect** [comment]
Thanks Jon,

That may very well be the case. I'm going to have to accept the intrusion of these messages in the logs

Thanks for your help anyway

Steve
