### ISSUE TITLE
[BUG] destinationSet.removeAllExcpept() should throw an error if an array is not passed

### ISSUE THREAD

**Issue by mhokanson** [nextgenhealthcare/connect#5876]
**Describe the bug**
destinationSet.removeAllExcpept() currently accepts strings with no issue, but if a string with a mis-typed destination name is sent the function fails to remove ANY destinations, leading to the possibility of sending PHI to unintended recipients. Per pacmane [here](https://github.com/nextgenhealthcare/connect/issues/5875#issuecomment-1668395064), this only occurs when a string is submitted instead of an array.

**To Reproduce**

1) Set up multiple destinations
2) In a source filter or transformer use destinationSet.removeAllExcept("<destination name>") with a typo in the <destination name> value
3) Process a message which would have triggered destination removal if the typo weren't present
4) Observe that no destinations were removed

**Expected behavior**
Either all destinations would be removed (removeAllExcept the channel that wasn't found) or an error should be thrown due to an invalid parameter type being submitted (Arrays apparently remove all destinations in this situation. Strings do not).

**Actual behavior**
When using destinationSet.removeAllExcept(<destination>) all destinations are enabled if no destinations match the supplied parameter.

**Environment**
OS: Windows 10, CentOS (version unknown)
Tested on Connect v3.10.1 (CentOS) and Connect v3.12.0 (Win 10)

**Workaround(s)**
1) Catch the output of destinationSet.removeAllExcept and perform a destinationSet.removeAll() if no destinations were removed.
2) Pass in an array instead of a string to the removeAllExcept() function

**Comment by jonbartels** [comment]
I use code like this and require it when my team uses destinationSet remove calls:

```
var removed = destinationSet.removeAllExcept('Some Destination Name');
if(!removed){
  throw "Destination 'some name' was not removed. This is a developer error!"
}
```

This code is useful for many destinationSet use cases. There are use cases where there are multiple operations, each of which could remove a destination; for these cases throwing an exception is NOT desirable.

I think that either:
1. This issue can be closed, since the return value for destinationSet.remove calls is a boolean that says if a remove was done. The need is addressed if the developer handles the returned boolean
OR
2. Specifically scoped to introduce a method like `removeAllExceptOrThrow` or `removeAllExceptLoudly` . 

The behavior of the existing methods cannot be changed without significantly impacting live code deployed in current Mirth releases. Any soultion must maintain the existing functionality and ADD new functionality for use cases where a thrown exception is desirable.

Note that the behavior from the code is pretty specific, **"at least one":**
```
     * @return A boolean indicating whether at least one destination connector was actually removed
     *         from processing for this message.
```

I think that mkhoanson has shown how DestinationSet remove calls can be improved but there is over a decade of existing code that relies on the current behaviors.

**Comment by mhokanson** [comment]
I have something like the code you shared in place now, but anyone only slightly familiar with the function, like new Mirth Developers, may easily run afoul of this issue and overshare PHI. I feel like the risk of oversharing PHI warrants either an error being thrown on a string being submitted, or the removal of all destinations EXCEPT direct matches, as I originally filed the bug report for: [https://github.com/nextgenhealthcare/connect/issues/5875](https://github.com/nextgenhealthcare/connect/issues/5875).

**Comment by pacmano1** [comment]
@mhokanson there are bazillion ways to overshare / accidentially share PHI due to programmer error, it's not really a great motivation for change and it's used to often to claim priority over other issues.

I think @jonbartels  makes a good point to protect existing code.   A middle ground might be a second optional boolean parameter that triggers a throw error if set to true.  If omitted assumes false.

**Comment by mhokanson** [comment]
I get it, but I still don't like that `removeAllExcept()` _doesn't_ `removeAllExcept ` if you supply a string and there is no matching Destination. There _are_ workarounds and, yes, it's been this way for over a decade now, but I still feel like it should removeAll or error if no match is found.

Maybe I'll finally learn enough Java to try and get this worked out and see how a pull request goes 🤷‍♂️

**Comment by jonbartels** [comment]
This is a fun discussion.

> Maybe I'll finally learn enough Java to try and get this worked out and see how a pull request goes

You have incredible luck. rogin is working on some improvements to DestinationSet to make it act like a regular Java Set and Collection. You can see what code is relevant and learn from his testing processes. Check out the code at: https://github.com/nextgenhealthcare/connect/compare/development...rogin:connect:4414-implement-set

> anyone only slightly familiar with the function, like new Mirth Developers
> I feel like the risk of oversharing PHI

These are both excellent points. I'll think on the issue today, the idea is solid and it's a question of HOW to implement the changes to not break existing workflows and make the code default to a safer posture.

**Comment by tonygermano** [comment]
I think this ticket should be closed. I've already reopened #5875 . I see where the bug in the code is, and it should work as @mhokanson expects.

**Comment by pladesma** [comment]
Closing as per tonygermano's comment.
